namespace Metapsi.Html;

/// <summary>
/// The DOM CompositionEvent represents events that occur due to the user indirectly entering text.
/// </summary>
public interface CompositionEvent : UIEvent
{
    /// <summary>
    /// The data read-only property of the CompositionEvent interface returns the characters generated by the input method that raised the event; its exact nature varies depending on the type of event that generated the CompositionEvent object.
    /// <para> For compositionstart events, this is the currently selected text that will be replaced by the string being composed.This value doesn't change even if content changes the selection range; rather, it indicates the string that was selected when composition started. </para>
    /// <para> For compositionupdate, this is the string as it stands currently as editing is ongoing. </para>
    /// <para> For compositionend events, this is the string as committed to the editor. </para>
    /// </summary>
    string data { get; }
}
