namespace Metapsi.Shoelace;

public static partial class Cdn
{
    public static string Version = "2.18.0";
    public static System.Collections.Generic.Dictionary<string,string> ImportPaths = new()
    {
        { "sl-alert", "components/alert/alert.js" },
        { "sl-animation", "components/animation/animation.js" },
        { "sl-animated-image", "components/animated-image/animated-image.js" },
        { "sl-avatar", "components/avatar/avatar.js" },
        { "sl-breadcrumb", "components/breadcrumb/breadcrumb.js" },
        { "sl-badge", "components/badge/badge.js" },
        { "sl-breadcrumb-item", "components/breadcrumb-item/breadcrumb-item.js" },
        { "sl-button", "components/button/button.js" },
        { "sl-button-group", "components/button-group/button-group.js" },
        { "sl-card", "components/card/card.js" },
        { "sl-carousel", "components/carousel/carousel.js" },
        { "sl-carousel-item", "components/carousel-item/carousel-item.js" },
        { "sl-checkbox", "components/checkbox/checkbox.js" },
        { "sl-color-picker", "components/color-picker/color-picker.js" },
        { "sl-copy-button", "components/copy-button/copy-button.js" },
        { "sl-details", "components/details/details.js" },
        { "sl-dialog", "components/dialog/dialog.js" },
        { "sl-divider", "components/divider/divider.js" },
        { "sl-drawer", "components/drawer/drawer.js" },
        { "sl-dropdown", "components/dropdown/dropdown.js" },
        { "sl-format-bytes", "components/format-bytes/format-bytes.js" },
        { "sl-format-date", "components/format-date/format-date.js" },
        { "sl-format-number", "components/format-number/format-number.js" },
        { "sl-icon", "components/icon/icon.js" },
        { "sl-icon-button", "components/icon-button/icon-button.js" },
        { "sl-image-comparer", "components/image-comparer/image-comparer.js" },
        { "sl-include", "components/include/include.js" },
        { "sl-input", "components/input/input.js" },
        { "sl-menu", "components/menu/menu.js" },
        { "sl-menu-item", "components/menu-item/menu-item.js" },
        { "sl-menu-label", "components/menu-label/menu-label.js" },
        { "sl-mutation-observer", "components/mutation-observer/mutation-observer.js" },
        { "sl-option", "components/option/option.js" },
        { "sl-progress-bar", "components/progress-bar/progress-bar.js" },
        { "sl-progress-ring", "components/progress-ring/progress-ring.js" },
        { "sl-qr-code", "components/qr-code/qr-code.js" },
        { "sl-radio", "components/radio/radio.js" },
        { "sl-radio-group", "components/radio-group/radio-group.js" },
        { "sl-range", "components/range/range.js" },
        { "sl-resize-observer", "components/resize-observer/resize-observer.js" },
        { "sl-rating", "components/rating/rating.js" },
        { "sl-relative-time", "components/relative-time/relative-time.js" },
        { "sl-radio-button", "components/radio-button/radio-button.js" },
        { "sl-select", "components/select/select.js" },
        { "sl-split-panel", "components/split-panel/split-panel.js" },
        { "sl-skeleton", "components/skeleton/skeleton.js" },
        { "sl-switch", "components/switch/switch.js" },
        { "sl-spinner", "components/spinner/spinner.js" },
        { "sl-tab-panel", "components/tab-panel/tab-panel.js" },
        { "sl-tab-group", "components/tab-group/tab-group.js" },
        { "sl-tab", "components/tab/tab.js" },
        { "sl-tag", "components/tag/tag.js" },
        { "sl-textarea", "components/textarea/textarea.js" },
        { "sl-tooltip", "components/tooltip/tooltip.js" },
        { "sl-tree", "components/tree/tree.js" },
        { "sl-tree-item", "components/tree-item/tree-item.js" },
        { "sl-visually-hidden", "components/visually-hidden/visually-hidden.js" },
    };
}
